import InvoiceModel from "../../models/invoice/invoiceModel.js";
import {InvoiceListTemplate} from "../../libs/templates/invoiceListTemplate.js";
import {Readable} from 'stream';
import UserModel from "../../models/user/userModel.js";

class InvoiceService {
    static async getAllInvoices(req, res) {
        const {userId} = req.user;
        const generatedInvoices = await InvoiceModel.find({userId}, {updatedAt: 0}, undefined);
        const user = await UserModel.findById(userId, {userName: 1}, undefined);

        if(!user){
            throw new Error("User not found");
        }

        const {userName} = user;

        if(!generatedInvoices[0]) {
            throw new Error(`No invoice generated by user ${userName}`);
        }

        const baseUrl = `${req.protocol}://${req.get('host')}`;

        const htmlContent =  InvoiceListTemplate.InvoiceListRender(generatedInvoices, userName, userId, baseUrl);

        const htmlStream = new Readable();
        htmlStream.push(htmlContent);
        htmlStream.push(null);

        return htmlStream;
    }
}

export default InvoiceService;
